<div class="chat-title">
    <h1>Servidor WebSocket</h1>
    <h2 class="nick">@localhost</h2>
    <figure class="avatar">
        <img src="https://w7.pngwing.com/pngs/419/473/png-transparent-computer-icons-user-profile-login-user-heroes-sphere-black-thumbnail.png" />
    </figure>
</div>
<div class="messages">
    <div class="messages-content"></div>
</div>
<div class="message-box">
    <textarea type="text" class="message-input" placeholder="Digite sua mensagem..."></textarea>
    <button type="submit" class="message-submit">Enviar</button>
</div>