<div id="container-conteudo">

    <?php
    $salaLiberada = false;
    foreach ($this->view->salas as $sala) :
        foreach ($sala as $salas) :
            $idSala = isset($_GET['id']) ? $_GET['id'] : false;
            if ($idSala == $salas['id']) {

                $codigoSala = $salas['codigo'];
                $idsala = $salas['id'];
                $idLider = $salas['idUserLider'];
                $_SESSION['idTurmaPostagem'] = $salas['id'];
                $salaLiberada = true;
                break;
            }
        endforeach;
    endforeach;

    if ($salaLiberada) {
    ?>
        <div class="sala">
            <div class="sala-conteudo">
                <p><a class="text-decoration-none text-reset" href="/sala?id=<?= $_SESSION['idTurmaPostagem'] ?>"><i class="fa-solid fa-arrow-left"></i><span class="ml-1">Voltar</span></a></p>
                <h2 class="container-titulo">Membros</h2>
                <div class="sala-membros mt-5">

                    <?php if (count($this->view->membros) > 0) { ?>
                        <?php $countMembros = 1; ?>

                        <?php foreach ($this->view->membros as $membros) : ?>
                            <div class="sala-membros-conteudo btn btn-light <?= count($this->view->membros) == $countMembros ? '' : 'menbros-line' ?> mt-3 <?= $this->view->ocupacao['ocupacao'] == 'docente' ? 'fx-betw-ctr' : 'fx-st-ctr' ?>">
                                <?php if ($this->view->ocupacao['ocupacao'] == 'docente') { ?>
                                    <div class="fx-st-ctr">
                                        <div class="sala-membros-conteudo-img">
                                            <img src="<?= $membros['foto'] == 'perfil.webp' ? '/assets/IMG/PERFIL/perfil.webp' : $membros['foto'] ?>" alt="Foto de perfil">
                                        </div>
                                        <div class="sala-membros-conteudo-texto fx-st-ctr">
                                            <?php if ($idLider == $membros['id']) { ?>
                                                <h2><?= $membros['nome'] ?> <span class="badge badge-primary">Líder</span></h2>
                                            <?php } else { ?>
                                                <h2><?= $membros['nome'] ?> </h2>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="membros-conteudo-dropwn fx-center pr-2">
                                        <i class="fas fa-ellipsis-v"></i>
                                        <div class="membros-conteudo-dropwn-content">
                                            <ul class="mb-0 px-2">
                                                <li class="px-2 py-2 btn btn-link"><a href="/app/sala/lider?id_user=<?= $membros['id'] ?>&id_sala=<?= $idsala ?>">Tornar lider</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                <?php } else { ?>
                                    <div class="sala-membros-conteudo-img">
                                        <img src="<?= $membros['foto'] == 'perfil.webp' ? '/assets/IMG/PERFIL/perfil.webp' : $membros['foto'] ?>" alt="Foto de perfil">
                                    </div>
                                    <div class="sala-membros-conteudo-texto fx-st-ctr">
                                        <?php if ($idLider == $membros['id']) { ?>
                                            <h2><?= $membros['nome'] ?> <span class="badge badge-primary">Líder</span></h2>
                                        <?php } else { ?>
                                            <h2><?= $membros['nome'] ?> </h2>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php $countMembros++; ?>
                        <?php endforeach; ?>


                    <?php } ?>

                </div>
            </div>
         
            <div class="sala-informacoes">
                <button class="sala-informacoes-toggle">
                    <i class="fa-solid fa-bars"></i>
                </button>
                <div class="informacoes-content">
                    <div class="calendar mb-4">
                        <div class="calendar-header">
                            <span class="month-picker" id="month-picker">Janeiro</span>
                            <div class="year-picker">
                                <span class="year-change" id="prev-year">
                                    <pre><</pre>
                                </span>
                                <span id="year"><?= date('Y'); ?></span>
                                <span class="year-change" id="next-year">
                                    <pre>></pre>
                                </span>
                            </div>
                        </div>
                        <div class="calendar-body">
                            <div class="calendar-week-day">
                                <div>Dom</div>
                                <div>Seg</div>
                                <div>Ter</div>
                                <div>Qua</div>
                                <div>Qui</div>
                                <div>Sex</div>
                                <div>Sab</div>
                            </div>
                            <div class="calendar-days"></div>
                        </div>
                        <div class="month-list"></div>
                    </div>
                    <div class="forms mt-4">
                        <h2 style="border-bottom: 3px solid <?= $salas['cor'] ?>;">Formulário</h2>
                        <?php if (count($this->view->viewEnquete) > 0) {
                            foreach ($this->view->viewEnquete as $viewEnquete) {
                        ?>
                                <a href="/enquete?id=<?= $idsala ?>&id_enquete=<?= $viewEnquete['id'] ?>" class="forms-content text-break mt-3 btn-light btn">
                                    <p class="text-break"><?= $viewEnquete['titulo'] ?></p>
                                    <div class="forms-time">
                                        <span class="forms-time-span-1">30min atrás</span>
                                        <span class="forms-time-span-2">Restam 4 dias</span>
                                    </div>
                                </a>
                        <?php
                            }
                        } else {
                            echo '<p class="text-secondary">Nenhuma enquete foi disponibilizada até o momento</p>';
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

    <?php } else {  ?>

        <h2 class="container-titulo">Tivemos um problema</h2>
        <p class="container-paragrafo mt-3">
            <?=
            $this->view->ocupacao['ocupacao'] == "discente" ?
                "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Faça parte de uma turma, insira o código de convite logo abaixo:" :
                "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Crie sua turma agora mesmo, insira as informações básicas logo abaixo:";
            ?>

        </p>
        <div class="container-formulario mt-5">
            <?php if ($this->view->ocupacao['ocupacao'] == "discente") { ?>
                <div id="adicionarsala-problema">
                    <div class="adicionarsala-conteudo" style="padding: 30px 0;">
                        <h3>Entrar na sala</h3>
                        <form action="/app/turma/entrar" method="post">
                            <input type="text" name="adicionarsalaCodigoTurma" placeholder="Código da turma" id="adicionarsalaCodigoTurma">
                            <div class="adicionarsala-codigo fx-center">
                                <input type="color" name="adicionarsalaColor" value="#3AA76D" id="adicionarsalaColor">
                                <input type="text" placeholder="Cor da turma" name="adicionarsalaCodigo" id="adicionarsalaCodigo">
                            </div>
                            <div class="adicionarsala-btn fx-st-ctr">
                                <button type="button" id="adicionarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                                <button type="submit" id="adicionarsala-btn-entrar" class="btn btn-success" style="margin-left: 0;">Entrar</button>
                            </div>
                        </form>
                    </div>
                </div>
            <?php } else { ?>
                <div id="adicionarsala-problema">
                    <div class="criarsala-conteudo" style="padding: 30px 0;">
                        <h3>Criar sala</h3>
                        <form action="/app/turma/criar" method="post">
                            <input type="text" name="criarsalaCodigoTurma" placeholder="Nome da turma" id="criarsalaCodigoTurma">
                            <div class="criarsala-codigo fx-center">
                                <input type="color" name="criarsalaColor" value="#3AA76D" id="criarsalaColor">
                                <input type="text" placeholder="Código da turma" value="#3AA76D" name="criarsalaCodigo" id="criarsalaCodigo">
                            </div>
                            <div class="criarsala-btn fx-st-ctr">
                                <button type="button" id="criarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                                <button type="submit" id="criarsala-btn-criar" class="btn btn-success" style="margin-left: 0;">Criar sala</button>
                            </div>
                        </form>
                    </div>
                </div>
            <?php } ?>
        </div>

    <?php }  ?>
</div>