<?php
$salaLiberada = false;
foreach ($this->view->salas as $sala) :
    foreach ($sala as $salas) :
        $idSala = isset($_GET['id']) ? $_GET['id'] : false;
        if ($idSala == $salas['id']) {

            $nomeSala = $salas['nome'];
            $idUserCriadorSala = $salas['idUserCriador'];
            $idUserLiderSala = $salas['idUserLider'];
            $codigoSala = $salas['codigo'];
            $_SESSION['idTurmaPostagem'] = $salas['id'];
            $salaLiberada = true;
            break;
        }
    endforeach;
endforeach;

if ($salaLiberada) {
?>
    <div class="sala">
        <div class="sala-conteudo pr-0">
            <div class="mensagem">
                <div class="mensagem-header fx-st-ctr">
                    <div class="mensagem-header-conteudo fx-center">
                        <div class="mensagem-header-conteudo-texto">
                            <h2><?= $nomeSala ?></h2>
                        </div>
                    </div>
                </div>
                <?php
                if ($idUserCriadorSala != $_SESSION['idUserOnline'] and $idUserLiderSala != $_SESSION['idUserOnline']) {
                    $classMessageSCLider = 'mensagem-conteudo-semLider';
                }else{
                    $classMessageSCLider = 'mensagem-conteudo-comLider';
                }
                ?>
                <div class="mensagem-conteudo messages <?= $classMessageSCLider ?>">
                    <div class="messages-content">
                        <?php
                        if (count($this->view->mensagens) > 0) {
                            foreach ($this->view->mensagens as $mensagem) {
                                if ($idUserCriadorSala != $_SESSION['idUserOnline'] and $idUserLiderSala != $_SESSION['idUserOnline']) {
                                    if ($mensagem['id_user_enviou'] == $idUserLiderSala) {
                                        echo '<div class="message message-personal new">' . $mensagem['texto'] . '</div>';
                                    } else {
                                        echo '<div class="message new" title=""><figure class="avatar"><img src="/assets/IMG/PERFIL/' . $mensagem['foto'] . '"></figure>' . $mensagem['nome'] . ': ' . $mensagem['texto'] . '</div>';
                                    }
                                } else {
                                    if ($mensagem['id_user_enviou'] == $_SESSION['idUserOnline']) {
                                        echo '<div class="message message-personal new">' . $mensagem['texto'] . '</div>';
                                    } else {
                                        echo '<div class="message new" title=""><figure class="avatar"><img src="/assets/IMG/PERFIL/' . $mensagem['foto'] . '"></figure>' . $mensagem['nome'] . ': ' . $mensagem['texto'] . '</div>';
                                    }
                                }
                            }
                        }else{
                            echo '<div class="mt-2 p-3 mb-2 bg-primary text-white">Nenhum histórico de conversa nesse bate papo</div>';
                        }
                        ?>
                    </div>
                    
                </div>
                <?php
                if ($idUserCriadorSala == $_SESSION['idUserOnline'] or $idUserLiderSala == $_SESSION['idUserOnline']) {
                    echo '<div class="mensagem-enviar fx-center">
                    <div class="mensagem-enviar-conteudo">
                        <div class="fx-betw-st">
                            <input placeholder="Digite sua mensagem" class="message-input" type="text" name="mensagem" id="mensagem">
                            <button type="submit"><i class="fas fa-paper-plane" class="message-submit" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>';
                }
                ?>

            </div>

        </div>
        <div class="sala-informacoes">
            <button class="sala-informacoes-toggle">
                <i class="fa-solid fa-bars"></i>
            </button>
            <div class="informacoes-content">
                <div class="listar_mensagens_recentes">
                    <h2>Mensagens recentes</h2>
                    <div class="listar_mensagens">
                        <?php if(count($this->view->recentes) > 0){
                            foreach($this->view->recentes as $recente){
                                $nomeUsuarioMessagem = explode(" ", $recente['nomeUsuario']);
                                echo '<a class="listar_conversa" href="/mensagem?id=' . $recente['id'] . '">
                                    <h2>'. $recente['nome'] .'</h2>
                                    <p>'. $nomeUsuarioMessagem[0] .': '. $recente['mensagem'] .'</p>
                                </a>';
                            }
                        }else{
                            echo '<p>Sinto muito em lhe informar, mas você não está presente em nenhuma sala</p>';
                        } ?>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php } else {  ?>

    <h2 class="container-titulo">Tivemos um problema</h2>
    <p class="container-paragrafo mt-3">
        <?=
        $this->view->ocupacao['ocupacao'] == "discente" ?
            "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Faça parte de uma turma, insira o código de convite logo abaixo:" :
            "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Crie sua turma agora mesmo, insira as informações básicas logo abaixo:";
        ?>

    </p>
    <div class="container-formulario mt-5">
        <?php if ($this->view->ocupacao['ocupacao'] == "discente") { ?>
            <div id="adicionarsala-problema">
                <div class="adicionarsala-conteudo" style="padding: 30px 0;">
                    <h3>Entrar na sala</h3>
                    <form action="/app/turma/entrar" method="post">
                        <input type="text" name="adicionarsalaCodigoTurma" placeholder="Código da turma" id="adicionarsalaCodigoTurma">
                        <div class="adicionarsala-codigo fx-center">
                            <input type="color" name="adicionarsalaColor" value="#3AA76D" id="adicionarsalaColor">
                            <input type="text" placeholder="Cor da turma" name="adicionarsalaCodigo" id="adicionarsalaCodigo">
                        </div>
                        <div class="adicionarsala-btn fx-st-ctr">
                            <button type="button" id="adicionarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                            <button type="submit" id="adicionarsala-btn-entrar" class="btn btn-success" style="margin-left: 0;">Entrar</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php } else { ?>
            <div id="adicionarsala-problema">
                <div class="criarsala-conteudo" style="padding: 30px 0;">
                    <h3>Criar sala</h3>
                    <form action="/app/turma/criar" method="post">
                        <input type="text" name="criarsalaCodigoTurma" placeholder="Nome da turma" id="criarsalaCodigoTurma">
                        <div class="criarsala-codigo fx-center">
                            <input type="color" name="criarsalaColor" value="#3AA76D" id="criarsalaColor">
                            <input type="text" placeholder="Código da turma" value="#3AA76D" name="criarsalaCodigo" id="criarsalaCodigo">
                        </div>
                        <div class="criarsala-btn fx-st-ctr">
                            <button type="button" id="criarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                            <button type="submit" id="criarsala-btn-criar" class="btn btn-success" style="margin-left: 0;">Criar sala</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php } ?>
    </div>
<?php }  ?>