<?php
$salaLiberada = false;
foreach ($this->view->salas as $sala) :
    foreach ($sala as $salas) :
        $idSala = isset($_GET['id']) ? $_GET['id'] : false;
        if ($idSala == $salas['id']) {

            $codigoSala = $salas['codigo'];
            $_SESSION['idTurmaPostagem'] = $salas['id'];
            $salaLiberada = true;
            break;
        }
    endforeach;
endforeach;

if ($salaLiberada) {
?>
    <div class="sala">
        <div class="sala-conteudo pr-0">
            <div class="mensagem">
                <div class="mensagem-header fx-st-ctr">
                    <div class="mensagem-header-conteudo fx-center">
                        <div class="mensagem-header-conteudo-foto">
                            <img src="/assets/IMG/PERFIL/perfil.webp" alt="foto de perfil do josé">
                        </div>
                        <div class="mensagem-header-conteudo-texto">
                            <h2>José Antonio</h2>
                            <p>On-line</p>
                        </div>
                    </div>
                </div>
                <div class="mensagem-conteudo messages">
                    <div class="messages-content">

                    </div>
                    <!--
                    <div class="mensagem-conteudo-msg fx-st-ctr">
                        <div class="mensagem-conteudo-msg-card">
                            <h2>José Antonio</h2>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis eligendi similique quo fugit aliquam placeat soluta molestias quaerat, sequi at libero iusto autem ex magni tenetur rem qui corporis asperiores?</p>
                            <p class="mesangem-data">2 horas atrás</p>
                        </div>
                    </div>
                    <div class="mensagem-conteudo-msg fx-end-ctr">
                        <div class="mensagem-conteudo-msg-card">
                            <h2>Você</h2>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis eligendi similique quo fugit aliquam placeat soluta molestias quaerat, sequi at libero iusto autem ex magni tenetur rem qui corporis asperiores?</p>
                            <p class="mesangem-data">2 horas atrás</p>
                        </div>
                    </div>
                    -->
                </div>
                <div class="mensagem-enviar fx-center">
                    <div class="mensagem-enviar-conteudo">
                        <div class="fx-betw-st">
                            <input placeholder="Digite sua mensagem" class="message-input" type="text" name="mensagem" id="mensagem">
                            <button type="submit"><i class="fas fa-paper-plane" class="message-submit" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="sala-informacoes">
            <button class="sala-informacoes-toggle">
                <i class="fa-solid fa-bars"></i>
            </button>
            <div class="informacoes-content">
                
            </div>
        </div>
    </div>

<?php } else {  ?>

    <h2 class="container-titulo">Tivemos um problema</h2>
    <p class="container-paragrafo mt-3">
        <?=
        $this->view->ocupacao['ocupacao'] == "discente" ?
            "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Faça parte de uma turma, insira o código de convite logo abaixo:" :
            "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Crie sua turma agora mesmo, insira as informações básicas logo abaixo:";
        ?>

    </p>
    <div class="container-formulario mt-5">
        <?php if ($this->view->ocupacao['ocupacao'] == "discente") { ?>
            <div id="adicionarsala-problema">
                <div class="adicionarsala-conteudo" style="padding: 30px 0;">
                    <h3>Entrar na sala</h3>
                    <form action="/app/turma/entrar" method="post">
                        <input type="text" name="adicionarsalaCodigoTurma" placeholder="Código da turma" id="adicionarsalaCodigoTurma">
                        <div class="adicionarsala-codigo fx-center">
                            <input type="color" name="adicionarsalaColor" value="#3AA76D" id="adicionarsalaColor">
                            <input type="text" placeholder="Cor da turma" name="adicionarsalaCodigo" id="adicionarsalaCodigo">
                        </div>
                        <div class="adicionarsala-btn fx-st-ctr">
                            <button type="button" id="adicionarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                            <button type="submit" id="adicionarsala-btn-entrar" class="btn btn-success" style="margin-left: 0;">Entrar</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php } else { ?>
            <div id="adicionarsala-problema">
                <div class="criarsala-conteudo" style="padding: 30px 0;">
                    <h3>Criar sala</h3>
                    <form action="/app/turma/criar" method="post">
                        <input type="text" name="criarsalaCodigoTurma" placeholder="Nome da turma" id="criarsalaCodigoTurma">
                        <div class="criarsala-codigo fx-center">
                            <input type="color" name="criarsalaColor" value="#3AA76D" id="criarsalaColor">
                            <input type="text" placeholder="Código da turma" value="#3AA76D" name="criarsalaCodigo" id="criarsalaCodigo">
                        </div>
                        <div class="criarsala-btn fx-st-ctr">
                            <button type="button" id="criarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                            <button type="submit" id="criarsala-btn-criar" class="btn btn-success" style="margin-left: 0;">Criar sala</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php } ?>
    </div>
<?php }  ?>