<div id="container-conteudo">

    <?php
    $salaLiberada = false;
    foreach ($this->view->salas as $sala) :
        foreach ($sala as $salas) :
            $idSala = isset($_GET['id']) ? $_GET['id'] : false;
            if ($idSala == $salas['id']) {

                $codigoSala = $salas['codigo'];
                $nomeSala = $salas['nome'];
                $idsala = $salas['id'];
                $_SESSION['idTurmaPostagem'] = $salas['id'];
                $salaLiberada = true;
                break;
            }
        endforeach;
    endforeach;
    if ($salaLiberada) {
    ?>
        <div class="sala h-auto">
            <div class="sala-conteudo">
                <h2 class="container-titulo"><?= $nomeSala ?></h2>
                <div class="container-acoes fx-betw-ctr mt-5">
                    <div class="container-acoes-left fx-center">
                        <h2><?= $this->view->ocupacao['ocupacao'] == "docente" ? 'Faça uma publicação' : 'Publicações recentes' ?></h2>
                    </div>
                    <div class="container-acoes-right fx-center">
                        <div class="container-acoes-button mr-3">
                            <button class="container-acoes-button-addmais fx-center">
                                <div class="container-acoes-button-copy fx-center" onclick="copiarCodigo()"><img class="container-img" draggable="false" src="/assets/IMG/icones/icone-copy.svg" alt="icone mais"></div><input type="text" class="ml-2 mr-2" id="codigo" readonly value="<?= $codigoSala ?>">
                            </button>
                        </div>
                        <div class="container-acoes-button">
                            <button class="container-acoes-button-addmais fx-center">
                                <a href="/membro?id=<?= $idSala ?>">
                                    <img class="container-img-addmais" draggable="false" src="/assets/IMG/icones/icone-person.svg" alt="icone mais"><span class="mr-3">Membros</span>
                                </a>
                            </button>
                        </div>
                    </div>
                </div>
                <?php if ($this->view->ocupacao['ocupacao'] == "docente") : ?>
                    <div class="container-conteudo-form mt-5 mb-5">
                        <form action="/app/postagem/criar" method="post" enctype="multipart/form-data">
                            <textarea name="conteudo" id="trumbowyg-editor" rows="5" placeholder="O que você quer perguntar?"></textarea>
                            <input type="hidden" value="<?= $idSala ?>" name="idturma">
                            <div class="div-conteudo-form fx-end-ctr">
                                <button class="btn-conteudo-form mt-3 btn btn-lg" type="submit">Postar</button>
                            </div>
                        </form>
                    </div>
                <?php endif; ?>
                <?php
                if ($this->view->postagens) {
                    foreach ($this->view->postagens as $postagens) : ?>
                        <div class="container-conteudo-postagens mt-3">
                            <div class="conteudo-postagens">
                                <div class="conteudo-postagens-top fx-betw-ctr">
                                    <div class="conteudo-postagens-top-nome fx-center">
                                        <div class="conteudo-postagens-top-nome-foto">
                                            <img src="<?= $postagens['foto'] == 'perfil.webp' ? '/assets/IMG/PERFIL/perfil.webp' : $postagens['foto'] ?>" alt="foto de perfil">
                                        </div>
                                        <div class="conteudo-postagens-top-nome-texto">
                                            <h2><?= $postagens['nome'] ?></h2>
                                        </div>
                                    </div>
                                    <div class="conteudo-postagens-top-data fx-center">
                                        <!--<p>12/04/2021, 6:37 p.m</p>-->
                                        <p>
                                            <?php
                                            $objDateTo = new \DateTime($postagens['data']);
                                            echo $objDateTo->format('d/m/Y H:i:s');
                                            ?>
                                        </p>
                                    </div>
                                </div>
                                <div class="conteudo-postagens-body mt-3">
                                    <?= $postagens['conteudo'] ?>
                                </div>
                            </div>
                        </div>
                    <?php
                    endforeach;
                } else { ?>
                    <div class="container-conteudo-postagem mt-5">
                        <p>Nenhuma postagem enviada até o momento</p>
                    </div>
                <?php } ?>
            </div>
            <div class="sala-informacoes">
                <button class="sala-informacoes-toggle">
                    <i class="fa-solid fa-bars"></i>
                </button>
                <div class="informacoes-content">
                    <div class="calendar mb-4">
                        <div class="calendar-header">
                            <span class="month-picker" id="month-picker">Janeiro</span>
                            <div class="year-picker">
                                <span class="year-change" id="prev-year">
                                    <pre><</pre>
                                </span>
                                <span id="year"><?= date('Y'); ?></span>
                                <span class="year-change" id="next-year">
                                    <pre>></pre>
                                </span>
                            </div>
                        </div>
                        <div class="calendar-body">
                            <div class="calendar-week-day">
                                <div>Dom</div>
                                <div>Seg</div>
                                <div>Ter</div>
                                <div>Qua</div>
                                <div>Qui</div>
                                <div>Sex</div>
                                <div>Sab</div>
                            </div>
                            <div class="calendar-days"></div>
                        </div>
                        <!--
                    <div class="calendar-footer">
                        <div class="toggle">
                            <span>Dark Mode</span>
                            <div class="dark-mode-switch">
                                <div class="dark-mode-switch-ident"></div>
                            </div>
                        </div>
                    </div>
                -->
                        <div class="month-list"></div>
                    </div>
                    <div class="forms mt-4">
                        <h2 style="border-bottom: 3px solid <?= $salas['cor'] ?>;">Formulário</h2>
                        <?php if (count($this->view->viewEnquete) > 0) {
                            foreach ($this->view->viewEnquete as $viewEnquete) {
                        ?>
                                <a href="/enquete?id=<?= $idsala ?>&id_enquete=<?= $viewEnquete['id'] ?>" class="forms-content text-break mt-3 btn-light btn">
                                    <p class="text-break"><?= $viewEnquete['titulo'] ?></p>
                                    <div class="forms-time">
                                        <span class="forms-time-span-1">30min atrás</span>
                                        <span class="forms-time-span-2">Restam 4 dias</span>
                                    </div>
                                </a>
                        <?php
                            }
                        } else {
                            echo '<p class="text-secondary">Nenhuma enquete foi disponibilizada até o momento</p>';
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

    <?php } else {  ?>

        <h2 class="container-titulo">Tivemos um problema</h2>
        <p class="container-paragrafo mt-3">
            <?=
            $this->view->ocupacao['ocupacao'] == "discente" ?
                "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Faça parte de uma turma, insira o código de convite logo abaixo:" :
                "Não conseguimos encontrar nenhuma sala com as informações que você nos informou. Crie sua turma agora mesmo, insira as informações básicas logo abaixo:";
            ?>

        </p>
        <div class="container-formulario mt-5">
            <?php if ($this->view->ocupacao['ocupacao'] == "discente") { ?>
                <div id="adicionarsala-problema">
                    <div class="adicionarsala-conteudo addAndCreatesala-conteudo" style="padding: 30px 0;">
                        <h3>Entrar na sala</h3>
                        <form action="/app/turma/entrar" method="post">
                            <input type="text" name="adicionarsalaCodigoTurma" placeholder="Código da turma" id="adicionarsalaCodigoTurma">
                            <div class="adicionarsala-codigo fx-center">
                                <input type="color" name="adicionarsalaColor" value="#3AA76D" id="adicionarsalaColor">
                                <input type="text" placeholder="Cor da turma" value="#3AA76D" name="adicionarsalaCodigo" id="adicionarsalaCodigo">
                            </div>
                            <div class="adicionarsala-btn fx-st-ctr">
                                <button type="button" id="adicionarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                                <button type="submit" id="adicionarsala-btn-entrar" class="btn btn-success" style="margin-left: 0;">Entrar</button>
                            </div>
                        </form>
                    </div>
                </div>
            <?php } else { ?>
                <div id="adicionarsala-problema">
                    <div class="criarsala-conteudo addAndCreatesala-conteudo" style="padding: 30px 0;">
                        <h3>Criar sala</h3>
                        <form action="/app/turma/criar" method="post">
                            <input type="text" name="criarsalaCodigoTurma" placeholder="Nome da turma" id="criarsalaCodigoTurma">
                            <div class="criarsala-codigo fx-center">
                                <input type="color" name="criarsalaColor" value="#3AA76D" id="criarsalaColor">
                                <input type="text" placeholder="Código da turma" value="#3AA76D" name="criarsalaCodigo" id="criarsalaCodigo">
                            </div>
                            <div class="criarsala-btn fx-st-ctr">
                                <button type="button" id="criarsala-btn-cancelar" class="btn btn-light" style="display: none;">Cancelar</button>
                                <button type="submit" id="criarsala-btn-criar" class="btn btn-success" style="margin-left: 0;">Criar sala</button>
                            </div>
                        </form>
                    </div>
                </div>
            <?php } ?>
        </div>

    <?php }  ?>
</div>