<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>WebSocket em PHP | By Eduardo Palandrani</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.min.css'>
    <link rel="stylesheet" href="assets/CSS/normalize.css">
    <link rel="stylesheet" href="assets/CSS/chat.min.css">
    <link rel="icon" type="image/png" href="https://cdn2.iconfinder.com/data/icons/servers-clouds-colored/80/websocket-web-socket-protocol-512.png">
</head>

<body>
    <div class="chat">
        <?= $this->content() ?>
    </div>
    <div class="bg"></div>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.concat.min.js'></script>
    <script src="assets/JS/chat.js"></script>
</body>

</html>
